### ISSUE TITLE
Icons

### ISSUE THREAD

**Issue by Kathleen-Chamberland** [Kathleen-Chamberland/action-hero-card-with-actions#1]
Im wondering how to submit the icons for this assignment, originally I had the individual icons and then I switched over to having all the icons grouped together either way mark bot won't let me submit 

@thomasjbradley

**Comment by thomasjbradley** [comment]
Did you use Spritebot to combine the icons together into a single file?

**Comment by Kathleen-Chamberland** [comment]
Forgot that step, will do that right now! thanks
